#!/usr/bin/env bash
# Wire openFrameworks → Ghost Room 77823 build.
# Usage:
#   ./scripts/setup-openframeworks.sh
#   ./scripts/setup-openframeworks.sh ~/openFrameworks
set -euo pipefail

CONSOLE="$(cd "$(dirname "$0")/.." && pwd)"
OF_ROOT="${1:-}"

compile_mk() {
  echo "$1/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk"
}

valid_of() {
  [[ -f "$(compile_mk "$1")" ]]
}

find_of() {
  local candidates=()
  if [[ -n "$OF_ROOT" ]]; then
    candidates+=("$OF_ROOT")
  else
    candidates+=(
      "$HOME/openFrameworks"
      "$HOME/Downloads/openFrameworks"
    )
    while IFS= read -r -d '' d; do candidates+=("$d"); done < <(
      find "$HOME/Downloads" -maxdepth 3 -type d \( -name 'openFrameworks' -o -name 'of_*' \) -print0 2>/dev/null || true
    )
  fi
  for dir in "${candidates[@]}"; do
    [[ -d "$dir" ]] || continue
    if valid_of "$dir"; then
      echo "$dir"
      return 0
    fi
    if [[ -d "$dir/openFrameworks" ]] && valid_of "$dir/openFrameworks"; then
      echo "$dir/openFrameworks"
      return 0
    fi
  done
  return 1
}

if ! OF_ROOT="$(find_of)"; then
  echo "Could not find a complete openFrameworks install."
  echo
  echo "Required file:"
  echo "  libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk"
  echo
  echo "Your Downloads folder may be missing the OF core (only libs/addons scripts)."
  echo "Recommended fix — clone the full release:"
  echo
  echo "  git clone --branch 0.12.1 --depth 1 https://github.com/openframeworks/openFrameworks.git ~/openFrameworks"
  echo "  cd ~/openFrameworks"
  echo "  ./scripts/osx/download_libs.sh"
  echo "  cd \"$CONSOLE\""
  echo "  ./scripts/setup-openframeworks.sh ~/openFrameworks"
  echo
  echo "Or re-unzip the full of_v0.12.1_osx_release.tar.gz from openframeworks.cc/download"
  echo "Then run: ./scripts/verify-openframeworks.sh ~/Downloads/of_v0.12.1_osx_release"
  exit 1
fi

echo "Found valid openFrameworks at:"
echo "  $OF_ROOT"
echo "  ✓ $(compile_mk "$OF_ROOT")"
echo

mkdir -p "$OF_ROOT/apps/myApps"
ln -sfn "$CONSOLE/openframeworks/GhostRoom77823" "$OF_ROOT/apps/myApps/GhostRoom77823"

ENV_FILE="$CONSOLE/launch.env"
if [[ -f "$ENV_FILE" ]]; then
  if grep -q '^export OF_ROOT=' "$ENV_FILE"; then
    sed -i '' "s|^export OF_ROOT=.*|export OF_ROOT=\"$OF_ROOT\"|" "$ENV_FILE"
  else
    echo "export OF_ROOT=\"$OF_ROOT\"" >>"$ENV_FILE"
  fi
else
  cp "$CONSOLE/launch.env.example" "$ENV_FILE"
  sed -i '' "s|^export OF_ROOT=.*|export OF_ROOT=\"$OF_ROOT\"|" "$ENV_FILE"
fi

echo "Updated launch.env → OF_ROOT=\"$OF_ROOT\""
echo "Linked GhostRoom77823 → $OF_ROOT/apps/myApps/GhostRoom77823"

LOCAL_MK="$CONSOLE/openframeworks/GhostRoom77823/config.make.local"
cat >"$LOCAL_MK" <<EOF
# Generated by setup-openframeworks.sh — do not commit.
OF_ROOT := $OF_ROOT
EOF
echo "Wrote config.make.local → OF_ROOT=$OF_ROOT"
echo
echo "Build and run:"
echo "  cd \"$OF_ROOT/apps/myApps/GhostRoom77823\""
echo "  make -j4 && make Run"
echo
read -r -p "Run download_libs.sh now? [y/N] " ans
if [[ "$ans" == "y" || "$ans" == "Y" ]]; then
  (cd "$OF_ROOT" && ./scripts/osx/download_libs.sh)
fi
echo
read -r -p "Run make now? [y/N] " ans2
if [[ "$ans2" == "y" || "$ans2" == "Y" ]]; then
  (cd "$OF_ROOT/apps/myApps/GhostRoom77823" && make -j4 && make Run)
fi
