#!/usr/bin/env python3
"""
Build a component bundle from traced / DSPG SVGs in reference/:

  1) reference/svg-components/registry.json  — machine-readable list + relative URLs
  2) reference/svg-components/split/<base>/  — one file per <g id="dspg-…"> in *_dspg.svg
  3) reference/svg-components/artifacts.mjs  — ESM loader + id map (for p5/Three/bundlers)

Re-run when you add or retrace SVGs:
  python3 build_svg_components.py

See COMPONENTS.md for how traced SVGs relate to procedural stroke output.
"""

from __future__ import annotations

import json
import os
import re
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
REF = os.path.join(HERE, "reference")
OUT_DIR = os.path.join(REF, "svg-components")
SPLIT_DIR = os.path.join(OUT_DIR, "split")

SVG_NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", SVG_NS)


def _strip_ns(tag: str) -> str:
    return tag.split("}", 1)[-1] if "}" in tag else tag


def _svg_tag_attribs(svg_el: ET.Element) -> tuple[str, str, str]:
    vb = svg_el.get("viewBox", "0 0 1024 768")
    w = svg_el.get("width", "1024")
    h = svg_el.get("height", "768")
    return vb, w, h


def _wrap_group_fragment(
    viewbox: str, width: str, height: str, group_el: ET.Element
) -> str:
    """Serialize a single <g> with parent SVG wrapper."""
    inner = ET.tostring(group_el, encoding="unicode", default_namespace=None)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f'<svg xmlns="{SVG_NS}" viewBox="{viewbox}" width="{width}" height="{height}">\n'
        f"{inner}\n</svg>\n"
    )


def _findall_dspg_groups(root: ET.Element) -> list[ET.Element]:
    out: list[ET.Element] = []
    for el in root.iter():
        if _strip_ns(el.tag) != "g":
            continue
        gid = el.get("id") or ""
        if gid.startswith("dspg-"):
            out.append(el)
    return out


def split_dspg_file(path: str, base_name: str) -> list[dict]:
    """Write each dspg-* group to split/<base_name>/<id>.svg; return file records."""
    tree = ET.parse(path)
    r = tree.getroot()
    if _strip_ns(r.tag) != "svg":
        return []
    vb, w, h = _svg_tag_attribs(r)
    base_out = os.path.join(SPLIT_DIR, base_name)
    os.makedirs(base_out, exist_ok=True)
    records: list[dict] = []
    for g in _findall_dspg_groups(r):
        gid = g.get("id", "group")
        safe = re.sub(r"[^\w\-.]+", "_", gid)
        fname = f"{safe}.svg"
        fpath = os.path.join(base_out, fname)
        with open(fpath, "w", encoding="utf-8") as f:
            f.write(_wrap_group_fragment(vb, w, h, g))
        rel = f"svg-components/split/{base_name}/{fname}"
        records.append(
            {
                "id": gid,
                "file": rel,
                "source": f"reference/{os.path.basename(path)}",
            }
        )
    return records


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    os.makedirs(SPLIT_DIR, exist_ok=True)

    # All SVGs in reference/ (not inside svg-components)
    all_svgs = [
        f
        for f in os.listdir(REF)
        if f.endswith(".svg") and os.path.isfile(os.path.join(REF, f))
    ]
    all_svgs.sort()

    registry: dict = {
        "base": "reference",
        "artifacts": [],
        "groups": [],
    }

    for name in all_svgs:
        full = os.path.join(REF, name)
        aid = os.path.splitext(name)[0]
        entry = {
            "id": aid,
            "file": f"reference/{name}",
            "kind": "dspg" if "_dspg" in name else "traced",
        }
        registry["artifacts"].append(entry)

        if "_dspg.svg" in name:
            base_name = aid  # e.g. artifact_dspg_3_dspg
            groups = split_dspg_file(full, base_name)
            for g in groups:
                g["bundle"] = base_name
            registry["groups"].extend(groups)

    reg_path = os.path.join(OUT_DIR, "registry.json")
    with open(reg_path, "w", encoding="utf-8") as f:
        json.dump(registry, f, indent=2)
        f.write("\n")

    # ESM loader for browsers / bundlers (paths relative to loop-snippets/)
    mjs = os.path.join(OUT_DIR, "artifacts.mjs")
    lines = [
        "// Auto-generated by build_svg_components.py",
        "/** @type {readonly { id: string, file: string, kind: string }[]} */",
        "export const ARTIFACTS = ",
        json.dumps(registry["artifacts"], indent=2),
        ";",
        "/** @type {readonly { id: string, file: string, source: string, bundle?: string }[]} */",
        "export const DSPG_GROUPS = ",
        json.dumps(registry["groups"], indent=2),
        ";",
        "",
        "/** @param {string} id @returns {{ id: string, file: string, kind: string } | undefined} */",
        "export function getArtifact(id) {",
        "  return ARTIFACTS.find((a) => a.id === id);",
        "}",
        "",
        "/** Fetch SVG text (same origin or GitHub Pages root). Base URL = page hosting folder. */",
        "export async function fetchArtifactSvg(id, baseUrl = '') {",
        "  const a = getArtifact(id);",
        "  if (!a) throw new Error(`Unknown artifact: ${id}`);",
        "  const url = baseUrl.replace(/\\/$/, '') + '/' + a.file;",
        "  const r = await fetch(url);",
        "  if (!r.ok) throw new Error(`Failed to load ${url}`);",
        "  return r.text();",
        "}",
        "",
        "/** @param {string} groupId e.g. dspg-dspg_3-traced */",
        "export function getDspgGroup(groupId) {",
        "  return DSPG_GROUPS.find((g) => g.id === groupId);",
        "}",
        "",
    ]
    with open(mjs, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Wrote {reg_path}")
    print(f"Wrote {mjs}")
    print(f"Split {len(registry['groups'])} DSPG groups under {SPLIT_DIR}/")
    print("  Open preview: reference/svg-components/preview.html (via local server)")


if __name__ == "__main__":
    main()
